#include "Defaults.hpp"
#include <array>

using namespace std::string_literals;

std::array trails = {
    matjson::makeObject({
        { "blend"s, matjson::Value(true) },
        { "tint"s, matjson::Value(true) },
        { "show"s, matjson::Value(false) },
        { "fade"s, matjson::Value(0.3) },
        { "stroke"s, matjson::Value(10.0) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(true) },
        { "tint"s, matjson::Value(false) },
        { "show"s, matjson::Value(false) },
        { "fade"s, matjson::Value(0.3) },
        { "stroke"s, matjson::Value(14.0) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(true) },
        { "tint"s, matjson::Value(true) },
        { "show"s, matjson::Value(false) },
        { "fade"s, matjson::Value(0.3) },
        { "stroke"s, matjson::Value(8.5) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(true) },
        { "tint"s, matjson::Value(true) },
        { "show"s, matjson::Value(false) },
        { "fade"s, matjson::Value(0.4) },
        { "stroke"s, matjson::Value(10.0) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(true) },
        { "tint"s, matjson::Value(true) },
        { "show"s, matjson::Value(true) },
        { "fade"s, matjson::Value(0.6) },
        { "stroke"s, matjson::Value(5.0) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(true) },
        { "tint"s, matjson::Value(true) },
        { "show"s, matjson::Value(true) },
        { "fade"s, matjson::Value(1.0) },
        { "stroke"s, matjson::Value(3.0) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(true) },
        { "tint"s, matjson::Value(false) },
        { "show"s, matjson::Value(false) },
        { "fade"s, matjson::Value(0.3) },
        { "stroke"s, matjson::Value(14.0) }
    })
};

matjson::Value defaultTrail = matjson::makeObject({
    { "blend"s, matjson::Value(true) },
    { "tint"s, matjson::Value(false) },
    { "show"s, matjson::Value(false) },
    { "fade"s, matjson::Value(0.3) },
    { "stroke"s, matjson::Value(14.0) }
});

const matjson::Value& Defaults::getTrailInfo(int id) {
    auto index = id - 1;
    return index >= 0 && index < trails.size() ? trails[index] : defaultTrail;
}

std::array deathEffects = {
    matjson::makeObject({
        { "blend"s, matjson::Value(false) },
        { "scale"s, matjson::Value(1.5) },
        { "scale-variance"s, matjson::Value(0.2) },
        { "rotation"s, matjson::Value(0.0) },
        { "rotation-variance"s, matjson::Value(45.0) },
        { "frame-delay"s, matjson::Value(0.055) },
        { "frame-delay-variance"s, matjson::Value(0.005) },
        { "fade"s, matjson::Value(true) },
        { "fade-delay-multiplier"s, matjson::Value(6.0) },
        { "fade-time-multiplier"s, matjson::Value(6.0) },
        { "circle-start-radius"s, matjson::Value(10.0) },
        { "circle-end-radius"s, matjson::Value(110.0) },
        { "circle-duration"s, matjson::Value(0.6) },
        { "circle-use-scale"s, matjson::Value(false) },
        { "circle-use-delay"s, matjson::Value(false) },
        { "outline-start-radius"s, matjson::Value(10.0) },
        { "outline-end-radius"s, matjson::Value(115.0) },
        { "outline-duration"s, matjson::Value(0.4) },
        { "outline-use-scale"s, matjson::Value(false) },
        { "outline-use-delay"s, matjson::Value(false) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(false) },
        { "scale"s, matjson::Value(1.2) },
        { "scale-variance"s, matjson::Value(0.2) },
        { "rotation"s, matjson::Value(0.0) },
        { "rotation-variance"s, matjson::Value(45.0) },
        { "frame-delay"s, matjson::Value(0.055) },
        { "frame-delay-variance"s, matjson::Value(0.005) },
        { "fade"s, matjson::Value(true) },
        { "fade-delay-multiplier"s, matjson::Value(6.0) },
        { "fade-time-multiplier"s, matjson::Value(6.0) },
        { "circle-start-radius"s, matjson::Value(10.0) },
        { "circle-end-radius"s, matjson::Value(110.0) },
        { "circle-duration"s, matjson::Value(0.5) },
        { "circle-use-scale"s, matjson::Value(false) },
        { "circle-use-delay"s, matjson::Value(false) },
        { "outline-start-radius"s, matjson::Value(10.0) },
        { "outline-end-radius"s, matjson::Value(115.0) },
        { "outline-duration"s, matjson::Value(0.4) },
        { "outline-use-scale"s, matjson::Value(false) },
        { "outline-use-delay"s, matjson::Value(false) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(false) },
        { "scale"s, matjson::Value(1.4) },
        { "scale-variance"s, matjson::Value(0.2) },
        { "rotation"s, matjson::Value(0.0) },
        { "rotation-variance"s, matjson::Value(45.0) },
        { "frame-delay"s, matjson::Value(0.0425) },
        { "frame-delay-variance"s, matjson::Value(0.0025) },
        { "fade"s, matjson::Value(true) },
        { "fade-delay-multiplier"s, matjson::Value(5.0) },
        { "fade-time-multiplier"s, matjson::Value(10.0) },
        { "circle-start-radius"s, matjson::Value(10.0) },
        { "circle-end-radius"s, matjson::Value(100.0) },
        { "circle-duration"s, matjson::Value(0.5) },
        { "circle-use-scale"s, matjson::Value(false) },
        { "circle-use-delay"s, matjson::Value(false) },
        { "outline-start-radius"s, matjson::Value(10.0) },
        { "outline-end-radius"s, matjson::Value(115.0) },
        { "outline-duration"s, matjson::Value(0.4) },
        { "outline-use-scale"s, matjson::Value(false) },
        { "outline-use-delay"s, matjson::Value(false) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(false) },
        { "scale"s, matjson::Value(1.2) },
        { "scale-variance"s, matjson::Value(0.1) },
        { "rotation"s, matjson::Value(0.0) },
        { "rotation-variance"s, matjson::Value(45.0) },
        { "frame-delay"s, matjson::Value(0.005) },
        { "frame-delay-variance"s, matjson::Value(0.05) },
        { "fade"s, matjson::Value(true) },
        { "fade-delay-multiplier"s, matjson::Value(8.0) },
        { "fade-time-multiplier"s, matjson::Value(6.0) },
        { "circle-start-radius"s, matjson::Value(10.0) },
        { "circle-end-radius"s, matjson::Value(110.0) },
        { "circle-duration"s, matjson::Value(0.5) },
        { "circle-use-scale"s, matjson::Value(false) },
        { "circle-use-delay"s, matjson::Value(false) },
        { "outline-start-radius"s, matjson::Value(10.0) },
        { "outline-end-radius"s, matjson::Value(115.0) },
        { "outline-duration"s, matjson::Value(0.4) },
        { "outline-use-scale"s, matjson::Value(false) },
        { "outline-use-delay"s, matjson::Value(false) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(false) },
        { "scale"s, matjson::Value(1.25) },
        { "scale-variance"s, matjson::Value(0.15) },
        { "rotation"s, matjson::Value(0.0) },
        { "rotation-variance"s, matjson::Value(45.0) },
        { "frame-delay"s, matjson::Value(0.05) },
        { "frame-delay-variance"s, matjson::Value(0.005) },
        { "fade"s, matjson::Value(true) },
        { "fade-delay-multiplier"s, matjson::Value(6.0) },
        { "fade-time-multiplier"s, matjson::Value(6.0) },
        { "circle-start-radius"s, matjson::Value(10.0) },
        { "circle-end-radius"s, matjson::Value(110.0) },
        { "circle-duration"s, matjson::Value(0.5) },
        { "circle-use-scale"s, matjson::Value(false) },
        { "circle-use-delay"s, matjson::Value(false) },
        { "outline-start-radius"s, matjson::Value(10.0) },
        { "outline-end-radius"s, matjson::Value(115.0) },
        { "outline-duration"s, matjson::Value(0.4) },
        { "outline-use-scale"s, matjson::Value(false) },
        { "outline-use-delay"s, matjson::Value(false) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(false) },
        { "scale"s, matjson::Value(1.3) },
        { "scale-variance"s, matjson::Value(0.15) },
        { "rotation"s, matjson::Value(0.0) },
        { "rotation-variance"s, matjson::Value(0.0) },
        { "frame-delay"s, matjson::Value(0.055) },
        { "frame-delay-variance"s, matjson::Value(0.0) },
        { "fade"s, matjson::Value(true) },
        { "fade-delay-multiplier"s, matjson::Value(8.0) },
        { "fade-time-multiplier"s, matjson::Value(6.0) },
        { "circle-start-radius"s, matjson::Value(10.0) },
        { "circle-end-radius"s, matjson::Value(110.0) },
        { "circle-duration"s, matjson::Value(0.6) },
        { "circle-use-scale"s, matjson::Value(true) },
        { "circle-use-delay"s, matjson::Value(false) },
        { "outline-start-radius"s, matjson::Value(10.0) },
        { "outline-end-radius"s, matjson::Value(115.0) },
        { "outline-duration"s, matjson::Value(0.4) },
        { "outline-use-scale"s, matjson::Value(true) },
        { "outline-use-delay"s, matjson::Value(false) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(false) },
        { "scale"s, matjson::Value(1.3) },
        { "scale-variance"s, matjson::Value(0.2) },
        { "rotation"s, matjson::Value(0.0) },
        { "rotation-variance"s, matjson::Value(90.0) },
        { "frame-delay"s, matjson::Value(0.0425) },
        { "frame-delay-variance"s, matjson::Value(0.0025) },
        { "fade"s, matjson::Value(true) },
        { "fade-delay-multiplier"s, matjson::Value(6.0) },
        { "fade-time-multiplier"s, matjson::Value(6.0) },
        { "circle-start-radius"s, matjson::Value(10.0) },
        { "circle-end-radius"s, matjson::Value(85.0) },
        { "circle-duration"s, matjson::Value(0.5) },
        { "circle-use-scale"s, matjson::Value(true) },
        { "circle-use-delay"s, matjson::Value(false) },
        { "outline-start-radius"s, matjson::Value(10.0) },
        { "outline-end-radius"s, matjson::Value(90.0) },
        { "outline-duration"s, matjson::Value(0.4) },
        { "outline-use-scale"s, matjson::Value(true) },
        { "outline-use-delay"s, matjson::Value(false) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(true) },
        { "scale"s, matjson::Value(0.85) },
        { "scale-variance"s, matjson::Value(0.05) },
        { "rotation"s, matjson::Value(-22.5) },
        { "rotation-variance"s, matjson::Value(22.5) },
        { "frame-delay"s, matjson::Value(0.05) },
        { "frame-delay-variance"s, matjson::Value(0.005) },
        { "fade"s, matjson::Value(true) },
        { "fade-delay-multiplier"s, matjson::Value(5.0) },
        { "fade-time-multiplier"s, matjson::Value(8.0) },
        { "circle-start-radius"s, matjson::Value(10.0) },
        { "circle-end-radius"s, matjson::Value(120.0) },
        { "circle-duration"s, matjson::Value(10.0) },
        { "circle-use-scale"s, matjson::Value(true) },
        { "circle-use-delay"s, matjson::Value(true) },
        { "outline-start-radius"s, matjson::Value(10.0) },
        { "outline-end-radius"s, matjson::Value(115.0) },
        { "outline-duration"s, matjson::Value(0.4) },
        { "outline-use-scale"s, matjson::Value(true) },
        { "outline-use-delay"s, matjson::Value(false) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(false) },
        { "scale"s, matjson::Value(1.0) },
        { "scale-variance"s, matjson::Value(0.1) },
        { "rotation"s, matjson::Value(0.0) },
        { "rotation-variance"s, matjson::Value(45.0) },
        { "frame-delay"s, matjson::Value(0.045) },
        { "frame-delay-variance"s, matjson::Value(0.005) },
        { "fade"s, matjson::Value(true) },
        { "fade-delay-multiplier"s, matjson::Value(10.0) },
        { "fade-time-multiplier"s, matjson::Value(3.0) },
        { "circle-start-radius"s, matjson::Value(10.0) },
        { "circle-end-radius"s, matjson::Value(120.0) },
        { "circle-duration"s, matjson::Value(0.6) },
        { "circle-use-scale"s, matjson::Value(false) },
        { "circle-use-delay"s, matjson::Value(false) },
        { "outline-start-radius"s, matjson::Value(10.0) },
        { "outline-end-radius"s, matjson::Value(125.0) },
        { "outline-duration"s, matjson::Value(0.4) },
        { "outline-use-scale"s, matjson::Value(false) },
        { "outline-use-delay"s, matjson::Value(false) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(true) },
        { "scale"s, matjson::Value(1.5) },
        { "scale-variance"s, matjson::Value(0.3) },
        { "rotation"s, matjson::Value(0.0) },
        { "rotation-variance"s, matjson::Value(0.0) },
        { "frame-delay"s, matjson::Value(0.035) },
        { "frame-delay-variance"s, matjson::Value(0.005) },
        { "fade"s, matjson::Value(true) },
        { "fade-delay-multiplier"s, matjson::Value(7.0) },
        { "fade-time-multiplier"s, matjson::Value(6.0) },
        { "circle-start-radius"s, matjson::Value(10.0) },
        { "circle-end-radius"s, matjson::Value(80.0) },
        { "circle-duration"s, matjson::Value(0.5) },
        { "circle-use-scale"s, matjson::Value(true) },
        { "circle-use-delay"s, matjson::Value(false) },
        { "outline-start-radius"s, matjson::Value(10.0) },
        { "outline-end-radius"s, matjson::Value(90.0) },
        { "outline-duration"s, matjson::Value(0.4) },
        { "outline-use-scale"s, matjson::Value(true) },
        { "outline-use-delay"s, matjson::Value(false) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(false) },
        { "scale"s, matjson::Value(1.25) },
        { "scale-variance"s, matjson::Value(0.1) },
        { "rotation"s, matjson::Value(0.0) },
        { "rotation-variance"s, matjson::Value(45.0) },
        { "frame-delay"s, matjson::Value(0.04) },
        { "frame-delay-variance"s, matjson::Value(0.005) },
        { "fade"s, matjson::Value(false) },
        { "fade-delay-multiplier"s, matjson::Value(7.0) },
        { "fade-time-multiplier"s, matjson::Value(6.0) },
        { "circle-start-radius"s, matjson::Value(10.0) },
        { "circle-end-radius"s, matjson::Value(125.0) },
        { "circle-duration"s, matjson::Value(0.5) },
        { "circle-use-scale"s, matjson::Value(true) },
        { "circle-use-delay"s, matjson::Value(false) },
        { "outline-start-radius"s, matjson::Value(10.0) },
        { "outline-end-radius"s, matjson::Value(135.0) },
        { "outline-duration"s, matjson::Value(0.4) },
        { "outline-use-scale"s, matjson::Value(true) },
        { "outline-use-delay"s, matjson::Value(false) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(false) },
        { "scale"s, matjson::Value(1.0) },
        { "scale-variance"s, matjson::Value(0.1) },
        { "rotation"s, matjson::Value(0.0) },
        { "rotation-variance"s, matjson::Value(45.0) },
        { "frame-delay"s, matjson::Value(0.04) },
        { "frame-delay-variance"s, matjson::Value(0.005) },
        { "fade"s, matjson::Value(false) },
        { "fade-delay-multiplier"s, matjson::Value(0.0) },
        { "fade-time-multiplier"s, matjson::Value(0.0) },
        { "circle-start-radius"s, matjson::Value(10.0) },
        { "circle-end-radius"s, matjson::Value(120.0) },
        { "circle-duration"s, matjson::Value(10.0) },
        { "circle-use-scale"s, matjson::Value(true) },
        { "circle-use-delay"s, matjson::Value(true) },
        { "outline-start-radius"s, matjson::Value(10.0) },
        { "outline-end-radius"s, matjson::Value(115.0) },
        { "outline-duration"s, matjson::Value(0.4) },
        { "outline-use-scale"s, matjson::Value(true) },
        { "outline-use-delay"s, matjson::Value(false) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(true) },
        { "scale"s, matjson::Value(1.2) },
        { "scale-variance"s, matjson::Value(0.2) },
        { "rotation"s, matjson::Value(180.0) },
        { "rotation-variance"s, matjson::Value(90.0) },
        { "frame-delay"s, matjson::Value(0.0475) },
        { "frame-delay-variance"s, matjson::Value(0.0025) },
        { "fade"s, matjson::Value(false) },
        { "fade-delay-multiplier"s, matjson::Value(0.0) },
        { "fade-time-multiplier"s, matjson::Value(0.0) },
        { "circle-start-radius"s, matjson::Value(8.0) },
        { "circle-end-radius"s, matjson::Value(96.0) },
        { "circle-duration"s, matjson::Value(10.0) },
        { "circle-use-scale"s, matjson::Value(true) },
        { "circle-use-delay"s, matjson::Value(true) },
        { "outline-start-radius"s, matjson::Value(8.0) },
        { "outline-end-radius"s, matjson::Value(92.0) },
        { "outline-duration"s, matjson::Value(0.4) },
        { "outline-use-scale"s, matjson::Value(true) },
        { "outline-use-delay"s, matjson::Value(false) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(true) },
        { "scale"s, matjson::Value(1.1) },
        { "scale-variance"s, matjson::Value(0.1) },
        { "rotation"s, matjson::Value(0.0) },
        { "rotation-variance"s, matjson::Value(45.0) },
        { "frame-delay"s, matjson::Value(0.035) },
        { "frame-delay-variance"s, matjson::Value(0.002) },
        { "fade"s, matjson::Value(false) },
        { "fade-delay-multiplier"s, matjson::Value(0.0) },
        { "fade-time-multiplier"s, matjson::Value(0.0) },
        { "circle-start-radius"s, matjson::Value(8.0) },
        { "circle-end-radius"s, matjson::Value(96.0) },
        { "circle-duration"s, matjson::Value(10.0) },
        { "circle-use-scale"s, matjson::Value(true) },
        { "circle-use-delay"s, matjson::Value(true) },
        { "outline-start-radius"s, matjson::Value(8.0) },
        { "outline-end-radius"s, matjson::Value(92.0) },
        { "outline-duration"s, matjson::Value(0.4) },
        { "outline-use-scale"s, matjson::Value(true) },
        { "outline-use-delay"s, matjson::Value(false) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(false) },
        { "scale"s, matjson::Value(1.6) },
        { "scale-variance"s, matjson::Value(0.2) },
        { "rotation"s, matjson::Value(180.0) },
        { "rotation-variance"s, matjson::Value(180.0) },
        { "frame-delay"s, matjson::Value(0.042) },
        { "frame-delay-variance"s, matjson::Value(0.002) },
        { "fade"s, matjson::Value(false) },
        { "fade-delay-multiplier"s, matjson::Value(0.0) },
        { "fade-time-multiplier"s, matjson::Value(0.0) },
        { "circle-start-radius"s, matjson::Value(8.0) },
        { "circle-end-radius"s, matjson::Value(72.0) },
        { "circle-duration"s, matjson::Value(10.0) },
        { "circle-use-scale"s, matjson::Value(true) },
        { "circle-use-delay"s, matjson::Value(true) },
        { "outline-start-radius"s, matjson::Value(8.0) },
        { "outline-end-radius"s, matjson::Value(64.0) },
        { "outline-duration"s, matjson::Value(14.0) },
        { "outline-use-scale"s, matjson::Value(true) },
        { "outline-use-delay"s, matjson::Value(true) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(false) },
        { "scale"s, matjson::Value(1.15) },
        { "scale-variance"s, matjson::Value(0.15) },
        { "rotation"s, matjson::Value(0.0) },
        { "rotation-variance"s, matjson::Value(0.0) },
        { "frame-delay"s, matjson::Value(0.0425) },
        { "frame-delay-variance"s, matjson::Value(0.0025) },
        { "fade"s, matjson::Value(true) },
        { "fade-delay-multiplier"s, matjson::Value(12.0) },
        { "fade-time-multiplier"s, matjson::Value(6.0) },
        { "circle-start-radius"s, matjson::Value(10.0) },
        { "circle-end-radius"s, matjson::Value(110.0) },
        { "circle-duration"s, matjson::Value(0.6) },
        { "circle-use-scale"s, matjson::Value(true) },
        { "circle-use-delay"s, matjson::Value(false) },
        { "outline-start-radius"s, matjson::Value(10.0) },
        { "outline-end-radius"s, matjson::Value(115.0) },
        { "outline-duration"s, matjson::Value(0.4) },
        { "outline-use-scale"s, matjson::Value(true) },
        { "outline-use-delay"s, matjson::Value(false) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(true) },
        { "scale"s, matjson::Value(1.1) },
        { "scale-variance"s, matjson::Value(0.1) },
        { "rotation"s, matjson::Value(0.0) },
        { "rotation-variance"s, matjson::Value(180.0) },
        { "frame-delay"s, matjson::Value(0.0375) },
        { "frame-delay-variance"s, matjson::Value(0.0025) },
        { "fade"s, matjson::Value(true) },
        { "fade-delay-multiplier"s, matjson::Value(12.0) },
        { "fade-time-multiplier"s, matjson::Value(6.0) },
        { "circle-start-radius"s, matjson::Value(10.0) },
        { "circle-end-radius"s, matjson::Value(90.0) },
        { "circle-duration"s, matjson::Value(0.5) },
        { "circle-use-scale"s, matjson::Value(false) },
        { "circle-use-delay"s, matjson::Value(false) },
        { "outline-start-radius"s, matjson::Value(10.0) },
        { "outline-end-radius"s, matjson::Value(100.0) },
        { "outline-duration"s, matjson::Value(0.4) },
        { "outline-use-scale"s, matjson::Value(false) },
        { "outline-use-delay"s, matjson::Value(false) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(false) },
        { "scale"s, matjson::Value(1.15) },
        { "scale-variance"s, matjson::Value(0.15) },
        { "rotation"s, matjson::Value(0.0) },
        { "rotation-variance"s, matjson::Value(180.0) },
        { "frame-delay"s, matjson::Value(0.0375) },
        { "frame-delay-variance"s, matjson::Value(0.0025) },
        { "fade"s, matjson::Value(true) },
        { "fade-delay-multiplier"s, matjson::Value(18.0) },
        { "fade-time-multiplier"s, matjson::Value(5.0) },
        { "circle-start-radius"s, matjson::Value(10.0) },
        { "circle-end-radius"s, matjson::Value(110.0) },
        { "circle-duration"s, matjson::Value(0.6) },
        { "circle-use-scale"s, matjson::Value(true) },
        { "circle-use-delay"s, matjson::Value(false) },
        { "outline-start-radius"s, matjson::Value(10.0) },
        { "outline-end-radius"s, matjson::Value(115.0) },
        { "outline-duration"s, matjson::Value(0.4) },
        { "outline-use-scale"s, matjson::Value(true) },
        { "outline-use-delay"s, matjson::Value(false) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(false) },
        { "scale"s, matjson::Value(1.15) },
        { "scale-variance"s, matjson::Value(0.15) },
        { "rotation"s, matjson::Value(0.0) },
        { "rotation-variance"s, matjson::Value(45.0) },
        { "frame-delay"s, matjson::Value(0.0425) },
        { "frame-delay-variance"s, matjson::Value(0.0025) },
        { "fade"s, matjson::Value(false) },
        { "fade-delay-multiplier"s, matjson::Value(0.0) },
        { "fade-time-multiplier"s, matjson::Value(0.0) },
        { "circle-start-radius"s, matjson::Value(10.0) },
        { "circle-end-radius"s, matjson::Value(110.0) },
        { "circle-duration"s, matjson::Value(0.6) },
        { "circle-use-scale"s, matjson::Value(true) },
        { "circle-use-delay"s, matjson::Value(false) },
        { "outline-start-radius"s, matjson::Value(10.0) },
        { "outline-end-radius"s, matjson::Value(115.0) },
        { "outline-duration"s, matjson::Value(0.4) },
        { "outline-use-scale"s, matjson::Value(true) },
        { "outline-use-delay"s, matjson::Value(false) }
    })
};

matjson::Value defaultDeathEffect = matjson::makeObject({
    { "blend"s, matjson::Value(false) },
    { "scale"s, matjson::Value(1.0) },
    { "scale-variance"s, matjson::Value(0.0) },
    { "rotation"s, matjson::Value(0.0) },
    { "rotation-variance"s, matjson::Value(0.0) },
    { "frame-delay"s, matjson::Value(0.05) },
    { "frame-delay-variance"s, matjson::Value(0.0) },
    { "fade"s, matjson::Value(true) },
    { "fade-delay-multiplier"s, matjson::Value(6.0) },
    { "fade-time-multiplier"s, matjson::Value(6.0) },
    { "circle-start-radius"s, matjson::Value(10.0) },
    { "circle-end-radius"s, matjson::Value(110.0) },
    { "circle-duration"s, matjson::Value(0.6) },
    { "circle-use-scale"s, matjson::Value(false) },
    { "circle-use-delay"s, matjson::Value(false) },
    { "outline-start-radius"s, matjson::Value(10.0) },
    { "outline-end-radius"s, matjson::Value(115.0) },
    { "outline-duration"s, matjson::Value(0.4) },
    { "outline-use-scale"s, matjson::Value(false) },
    { "outline-use-delay"s, matjson::Value(false) }
});

const matjson::Value& Defaults::getDeathEffectInfo(int id) {
    auto index = id - 2;
    return index >= 0 && index < deathEffects.size() ? deathEffects[index] : defaultDeathEffect;
}

std::array shipFires = {
    matjson::makeObject({
        { "blend"s, matjson::Value(true) },
        { "fade"s, matjson::Value(0.0636) },
        { "stroke"s, matjson::Value(22.0) },
        { "interval"s, matjson::Value(1.0 / 32.0) },
        { "x"s, matjson::Value(-8.0) },
        { "y"s, matjson::Value(-3.0) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(true) },
        { "fade"s, matjson::Value(0.1278) },
        { "stroke"s, matjson::Value(28.6) },
        { "interval"s, matjson::Value(1.0 / 32.0) },
        { "x"s, matjson::Value(-8.0) },
        { "y"s, matjson::Value(-3.5) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(true) },
        { "fade"s, matjson::Value(0.105) },
        { "stroke"s, matjson::Value(28.6) },
        { "interval"s, matjson::Value(1.0 / 24.0) },
        { "x"s, matjson::Value(-14.0) },
        { "y"s, matjson::Value(-3.0) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(true) },
        { "fade"s, matjson::Value(0.09) },
        { "stroke"s, matjson::Value(18.7) },
        { "interval"s, matjson::Value(1.0 / 20.0) },
        { "x"s, matjson::Value(-14.0) },
        { "y"s, matjson::Value(-3.0) }
    }),
    matjson::makeObject({
        { "blend"s, matjson::Value(true) },
        { "fade"s, matjson::Value(0.096) },
        { "stroke"s, matjson::Value(27.0) },
        { "interval"s, matjson::Value(1.0 / 24.0) },
        { "x"s, matjson::Value(-14.0) },
        { "y"s, matjson::Value(-2.5) }
    })
};

matjson::Value defaultShipFire = matjson::makeObject({
    { "blend"s, matjson::Value(true) },
    { "fade"s, matjson::Value(0.1) },
    { "stroke"s, matjson::Value(20.0) },
    { "interval"s, matjson::Value(0.05) },
    { "x"s, matjson::Value(-8.0) },
    { "y"s, matjson::Value(-3.0) }
});

const matjson::Value& Defaults::getShipFireInfo(int id) {
    auto index = id - 2;
    return index >= 0 && index < shipFires.size() ? shipFires[index] : defaultShipFire;
}

int Defaults::getShipFireCount(int id) {
    switch (id) {
        case 2: return 9;
        case 3: return 10;
        case 4: return 6;
        case 5: return 16;
        case 6: return 5;
        default: return 0;
    }
}
