#include "Defaults.hpp"
#include <array>

std::array trails = {
    matjson::makeObject({
        { "blend", true },
        { "tint", true },
        { "show", false },
        { "fade", 0.3f },
        { "stroke", 10.0f }
    }),
    matjson::makeObject({
        { "blend", true },
        { "tint", false },
        { "show", false },
        { "fade", 0.3f },
        { "stroke", 14.0f }
    }),
    matjson::makeObject({
        { "blend", true },
        { "tint", true },
        { "show", false },
        { "fade", 0.3f },
        { "stroke", 8.5f }
    }),
    matjson::makeObject({
        { "blend", true },
        { "tint", true },
        { "show", false },
        { "fade", 0.4f },
        { "stroke", 10.0f }
    }),
    matjson::makeObject({
        { "blend", true },
        { "tint", true },
        { "show", true },
        { "fade", 0.6f },
        { "stroke", 5.0f }
    }),
    matjson::makeObject({
        { "blend", true },
        { "tint", true },
        { "show", true },
        { "fade", 1.0f },
        { "stroke", 3.0f }
    }),
    matjson::makeObject({
        { "blend", true },
        { "tint", false },
        { "show", false },
        { "fade", 0.3f },
        { "stroke", 14.0f }
    })
};

matjson::Value defaultTrail = matjson::makeObject({
    { "blend", true },
    { "tint", false },
    { "show", false },
    { "fade", 0.3f },
    { "stroke", 14.0f }
});

const matjson::Value& Defaults::getTrailInfo(int id) {
    auto index = id - 1;
    return index >= 0 && index < trails.size() ? trails[index] : defaultTrail;
}

std::array deathEffects = {
    matjson::makeObject({ // 2
        { "blend", false },
        { "scale", 1.5f },
        { "scale-variance", 0.2f },
        { "rotation", 0.0f },
        { "rotation-variance", 45.0f },
        { "frame-delay", 0.055f },
        { "frame-delay-variance", 0.005f },
        { "fade", true },
        { "fade-delay-multiplier", 6.0f },
        { "fade-time-multiplier", 6.0f },
        { "circle-start-radius", 10.0f },
        { "circle-end-radius", 110.0f },
        { "circle-duration", 0.6f },
        { "circle-use-scale", false },
        { "circle-use-delay", false },
        { "outline-start-radius", 10.0f },
        { "outline-end-radius", 115.0f },
        { "outline-duration", 0.4f },
        { "outline-use-scale", false },
        { "outline-use-delay", false }
    }),
    matjson::makeObject({ // 3
        { "blend", false },
        { "scale", 1.2f },
        { "scale-variance", 0.2f },
        { "rotation", 0.0f },
        { "rotation-variance", 45.0f },
        { "frame-delay", 0.055f },
        { "frame-delay-variance", 0.005f },
        { "fade", true },
        { "fade-delay-multiplier", 6.0f },
        { "fade-time-multiplier", 6.0f },
        { "circle-start-radius", 10.0f },
        { "circle-end-radius", 110.0f },
        { "circle-duration", 0.5f },
        { "circle-use-scale", false },
        { "circle-use-delay", false },
        { "outline-start-radius", 10.0f },
        { "outline-end-radius", 115.0f },
        { "outline-duration", 0.4f },
        { "outline-use-scale", false },
        { "outline-use-delay", false }
    }),
    matjson::makeObject({ // 4
        { "blend", false },
        { "scale", 1.4f },
        { "scale-variance", 0.2f },
        { "rotation", 0.0f },
        { "rotation-variance", 45.0f },
        { "frame-delay", 0.0425f },
        { "frame-delay-variance", 0.0025f },
        { "fade", true },
        { "fade-delay-multiplier", 5.0f },
        { "fade-time-multiplier", 10.0f },
        { "circle-start-radius", 10.0f },
        { "circle-end-radius", 100.0f },
        { "circle-duration", 0.5f },
        { "circle-use-scale", false },
        { "circle-use-delay", false },
        { "outline-start-radius", 10.0f },
        { "outline-end-radius", 115.0f },
        { "outline-duration", 0.4f },
        { "outline-use-scale", false },
        { "outline-use-delay", false }
    }),
    matjson::makeObject({ // 5
        { "blend", false },
        { "scale", 1.2f },
        { "scale-variance", 0.1f },
        { "rotation", 0.0f },
        { "rotation-variance", 45.0f },
        { "frame-delay", 0.005f },
        { "frame-delay-variance", 0.05f },
        { "fade", true },
        { "fade-delay-multiplier", 8.0f },
        { "fade-time-multiplier", 6.0f },
        { "circle-start-radius", 10.0f },
        { "circle-end-radius", 110.0f },
        { "circle-duration", 0.5f },
        { "circle-use-scale", false },
        { "circle-use-delay", false },
        { "outline-start-radius", 10.0f },
        { "outline-end-radius", 115.0f },
        { "outline-duration", 0.4f },
        { "outline-use-scale", false },
        { "outline-use-delay", false }
    }),
    matjson::makeObject({ // 6
        { "blend", false },
        { "scale", 1.25f },
        { "scale-variance", 0.15f },
        { "rotation", 0.0f },
        { "rotation-variance", 45.0f },
        { "frame-delay", 0.05f },
        { "frame-delay-variance", 0.005f },
        { "fade", true },
        { "fade-delay-multiplier", 6.0f },
        { "fade-time-multiplier", 6.0f },
        { "circle-start-radius", 10.0f },
        { "circle-end-radius", 110.0f },
        { "circle-duration", 0.5f },
        { "circle-use-scale", false },
        { "circle-use-delay", false },
        { "outline-start-radius", 10.0f },
        { "outline-end-radius", 115.0f },
        { "outline-duration", 0.4f },
        { "outline-use-scale", false },
        { "outline-use-delay", false }
    }),
    matjson::makeObject({ // 7
        { "blend", false },
        { "scale", 1.3f },
        { "scale-variance", 0.15f },
        { "rotation", 0.0f },
        { "rotation-variance", 0.0f },
        { "frame-delay", 0.055f },
        { "frame-delay-variance", 0.0f },
        { "fade", true },
        { "fade-delay-multiplier", 8.0f },
        { "fade-time-multiplier", 6.0f },
        { "circle-start-radius", 10.0f },
        { "circle-end-radius", 110.0f },
        { "circle-duration", 0.6f },
        { "circle-use-scale", true },
        { "circle-use-delay", false },
        { "outline-start-radius", 10.0f },
        { "outline-end-radius", 115.0f },
        { "outline-duration", 0.4f },
        { "outline-use-scale", true },
        { "outline-use-delay", false }
    }),
    matjson::makeObject({ // 8
        { "blend", false },
        { "scale", 1.3f },
        { "scale-variance", 0.2f },
        { "rotation", 0.0f },
        { "rotation-variance", 90.0f },
        { "frame-delay", 0.0425f },
        { "frame-delay-variance", 0.0025f },
        { "fade", true },
        { "fade-delay-multiplier", 6.0f },
        { "fade-time-multiplier", 6.0f },
        { "circle-start-radius", 10.0f },
        { "circle-end-radius", 85.0f },
        { "circle-duration", 0.5f },
        { "circle-use-scale", true },
        { "circle-use-delay", false },
        { "outline-start-radius", 10.0f },
        { "outline-end-radius", 90.0f },
        { "outline-duration", 0.4f },
        { "outline-use-scale", true },
        { "outline-use-delay", false }
    }),
    matjson::makeObject({ // 9
        { "blend", true },
        { "scale", 0.85f },
        { "scale-variance", 0.05f },
        { "rotation", -22.5f },
        { "rotation-variance", 22.5f },
        { "frame-delay", 0.05f },
        { "frame-delay-variance", 0.005f },
        { "fade", true },
        { "fade-delay-multiplier", 5.0f },
        { "fade-time-multiplier", 8.0f },
        { "circle-start-radius", 10.0f },
        { "circle-end-radius", 120.0f },
        { "circle-duration", 10.0f },
        { "circle-use-scale", true },
        { "circle-use-delay", true },
        { "outline-start-radius", 10.0f },
        { "outline-end-radius", 115.0f },
        { "outline-duration", 0.4f },
        { "outline-use-scale", true },
        { "outline-use-delay", false }
    }),
    matjson::makeObject({ // 10
        { "blend", false },
        { "scale", 1.0f },
        { "scale-variance", 0.1f },
        { "rotation", 0.0f },
        { "rotation-variance", 45.0f },
        { "frame-delay", 0.045f },
        { "frame-delay-variance", 0.005f },
        { "fade", true },
        { "fade-delay-multiplier", 10.0f },
        { "fade-time-multiplier", 3.0f },
        { "circle-start-radius", 10.0f },
        { "circle-end-radius", 120.0f },
        { "circle-duration", 0.6f },
        { "circle-use-scale", false },
        { "circle-use-delay", false },
        { "outline-start-radius", 10.0f },
        { "outline-end-radius", 125.0f },
        { "outline-duration", 0.4f },
        { "outline-use-scale", false },
        { "outline-use-delay", false }
    }),
    matjson::makeObject({ // 11
        { "blend", true },
        { "scale", 1.5f },
        { "scale-variance", 0.3f },
        { "rotation", 0.0f },
        { "rotation-variance", 0.0f },
        { "frame-delay", 0.035f },
        { "frame-delay-variance", 0.005f },
        { "fade", true },
        { "fade-delay-multiplier", 7.0f },
        { "fade-time-multiplier", 6.0f },
        { "circle-start-radius", 10.0f },
        { "circle-end-radius", 80.0f },
        { "circle-duration", 0.5f },
        { "circle-use-scale", true },
        { "circle-use-delay", false },
        { "outline-start-radius", 10.0f },
        { "outline-end-radius", 90.0f },
        { "outline-duration", 0.4f },
        { "outline-use-scale", true },
        { "outline-use-delay", false }
    }),
    matjson::makeObject({ // 12
        { "blend", false },
        { "scale", 1.25f },
        { "scale-variance", 0.1f },
        { "rotation", 0.0f },
        { "rotation-variance", 45.0f },
        { "frame-delay", 0.04f },
        { "frame-delay-variance", 0.005f },
        { "fade", false },
        { "fade-delay-multiplier", 7.0f },
        { "fade-time-multiplier", 6.0f },
        { "circle-start-radius", 10.0f },
        { "circle-end-radius", 125.0f },
        { "circle-duration", 0.5f },
        { "circle-use-scale", true },
        { "circle-use-delay", false },
        { "outline-start-radius", 10.0f },
        { "outline-end-radius", 135.0f },
        { "outline-duration", 0.4f },
        { "outline-use-scale", true },
        { "outline-use-delay", false }
    }),
    matjson::makeObject({ // 13
        { "blend", false },
        { "scale", 1.0f },
        { "scale-variance", 0.1f },
        { "rotation", 0.0f },
        { "rotation-variance", 45.0f },
        { "frame-delay", 0.04f },
        { "frame-delay-variance", 0.005f },
        { "fade", false },
        { "fade-delay-multiplier", 0.0f },
        { "fade-time-multiplier", 0.0f },
        { "circle-start-radius", 10.0f },
        { "circle-end-radius", 120.0f },
        { "circle-duration", 10.0f },
        { "circle-use-scale", true },
        { "circle-use-delay", true },
        { "outline-start-radius", 10.0f },
        { "outline-end-radius", 115.0f },
        { "outline-duration", 0.4f },
        { "outline-use-scale", true },
        { "outline-use-delay", false }
    }),
    matjson::makeObject({ // 14
        { "blend", true },
        { "scale", 1.2f },
        { "scale-variance", 0.2f },
        { "rotation", 180.0f },
        { "rotation-variance", 90.0f },
        { "frame-delay", 0.0475f },
        { "frame-delay-variance", 0.0025f },
        { "fade", false },
        { "fade-delay-multiplier", 0.0f },
        { "fade-time-multiplier", 0.0f },
        { "circle-start-radius", 8.0f },
        { "circle-end-radius", 96.0f },
        { "circle-duration", 10.0f },
        { "circle-use-scale", true },
        { "circle-use-delay", true },
        { "outline-start-radius", 8.0f },
        { "outline-end-radius", 92.0f },
        { "outline-duration", 0.4f },
        { "outline-use-scale", true },
        { "outline-use-delay", false }
    }),
    matjson::makeObject({ // 15
        { "blend", true },
        { "scale", 1.1f },
        { "scale-variance", 0.1f },
        { "rotation", 0.0f },
        { "rotation-variance", 45.0f },
        { "frame-delay", 0.035f },
        { "frame-delay-variance", 0.002f },
        { "fade", false },
        { "fade-delay-multiplier", 0.0f },
        { "fade-time-multiplier", 0.0f },
        { "circle-start-radius", 8.0f },
        { "circle-end-radius", 96.0f },
        { "circle-duration", 10.0f },
        { "circle-use-scale", true },
        { "circle-use-delay", true },
        { "outline-start-radius", 8.0f },
        { "outline-end-radius", 92.0f },
        { "outline-duration", 0.4f },
        { "outline-use-scale", true },
        { "outline-use-delay", false }
    }),
    matjson::makeObject({ // 16
        { "blend", false },
        { "scale", 1.6f },
        { "scale-variance", 0.2f },
        { "rotation", 180.0f },
        { "rotation-variance", 180.0f },
        { "frame-delay", 0.042f },
        { "frame-delay-variance", 0.002f },
        { "fade", false },
        { "fade-delay-multiplier", 0.0f },
        { "fade-time-multiplier", 0.0f },
        { "circle-start-radius", 8.0f },
        { "circle-end-radius", 72.0f },
        { "circle-duration", 10.0f },
        { "circle-use-scale", true },
        { "circle-use-delay", true },
        { "outline-start-radius", 8.0f },
        { "outline-end-radius", 64.0f },
        { "outline-duration", 14.0f },
        { "outline-use-scale", true },
        { "outline-use-delay", true }
    }),
    matjson::makeObject({ // 17
        { "blend", false },
        { "scale", 1.15f },
        { "scale-variance", 0.15f },
        { "rotation", 0.0f },
        { "rotation-variance", 0.0f },
        { "frame-delay", 0.0425f },
        { "frame-delay-variance", 0.0025f },
        { "fade", true },
        { "fade-delay-multiplier", 12.0f },
        { "fade-time-multiplier", 6.0f },
        { "circle-start-radius", 10.0f },
        { "circle-end-radius", 110.0f },
        { "circle-duration", 0.6f },
        { "circle-use-scale", true },
        { "circle-use-delay", false },
        { "outline-start-radius", 10.0f },
        { "outline-end-radius", 115.0f },
        { "outline-duration", 0.4f },
        { "outline-use-scale", true },
        { "outline-use-delay", false }
    }),
    matjson::makeObject({ // 18
        { "blend", true },
        { "scale", 1.1f },
        { "scale-variance", 0.1f },
        { "rotation", 0.0f },
        { "rotation-variance", 180.0f },
        { "frame-delay", 0.0375f },
        { "frame-delay-variance", 0.0025f },
        { "fade", true },
        { "fade-delay-multiplier", 12.0f },
        { "fade-time-multiplier", 6.0f },
        { "circle-start-radius", 10.0f },
        { "circle-end-radius", 90.0f },
        { "circle-duration", 0.5f },
        { "circle-use-scale", false },
        { "circle-use-delay", false },
        { "outline-start-radius", 10.0f },
        { "outline-end-radius", 100.0f },
        { "outline-duration", 0.4f },
        { "outline-use-scale", false },
        { "outline-use-delay", false }
    }),
    matjson::makeObject({ // 19
        { "blend", false },
        { "scale", 1.15f },
        { "scale-variance", 0.15f },
        { "rotation", 0.0f },
        { "rotation-variance", 180.0f },
        { "frame-delay", 0.0375f },
        { "frame-delay-variance", 0.0025f },
        { "fade", true },
        { "fade-delay-multiplier", 18.0f },
        { "fade-time-multiplier", 5.0f },
        { "circle-start-radius", 10.0f },
        { "circle-end-radius", 110.0f },
        { "circle-duration", 0.6f },
        { "circle-use-scale", true },
        { "circle-use-delay", false },
        { "outline-start-radius", 10.0f },
        { "outline-end-radius", 115.0f },
        { "outline-duration", 0.4f },
        { "outline-use-scale", true },
        { "outline-use-delay", false }
    }),
    matjson::makeObject({ // 20
        { "blend", false },
        { "scale", 1.15f },
        { "scale-variance", 0.15f },
        { "rotation", 0.0f },
        { "rotation-variance", 45.0f },
        { "frame-delay", 0.0425f },
        { "frame-delay-variance", 0.0025f },
        { "fade", false },
        { "fade-delay-multiplier", 0.0f },
        { "fade-time-multiplier", 0.0f },
        { "circle-start-radius", 10.0f },
        { "circle-end-radius", 110.0f },
        { "circle-duration", 0.6f },
        { "circle-use-scale", true },
        { "circle-use-delay", false },
        { "outline-start-radius", 10.0f },
        { "outline-end-radius", 115.0f },
        { "outline-duration", 0.4f },
        { "outline-use-scale", true },
        { "outline-use-delay", false }
    })
};

matjson::Value defaultDeathEffect = matjson::makeObject({
    { "blend", false },
    { "scale", 1.0f },
    { "scale-variance", 0.0f },
    { "rotation", 0.0f },
    { "rotation-variance", 0.0f },
    { "frame-delay", 0.05f },
    { "frame-delay-variance", 0.0f },
    { "fade", true },
    { "fade-delay-multiplier", 6.0f },
    { "fade-time-multiplier", 6.0f },
    { "circle-start-radius", 10.0f },
    { "circle-end-radius", 110.0f },
    { "circle-duration", 0.6f },
    { "circle-use-scale", false },
    { "circle-use-delay", false },
    { "outline-start-radius", 10.0f },
    { "outline-end-radius", 115.0f },
    { "outline-duration", 0.4f },
    { "outline-use-scale", false },
    { "outline-use-delay", false }
});

const matjson::Value& Defaults::getDeathEffectInfo(int id) {
    auto index = id - 2;
    return index >= 0 && index < deathEffects.size() ? deathEffects[index] : defaultDeathEffect;
}

std::array shipFires = {
    matjson::makeObject({
        { "blend", true },
        { "fade", 0.0636f },
        { "stroke", 22.0f },
        { "interval", 1.0f / 32.0f },
        { "x", -8.0f },
        { "y", -3.0f }
    }),
    matjson::makeObject({
        { "blend", true },
        { "fade", 0.1278f },
        { "stroke", 28.6f },
        { "interval", 1.0f / 32.0f },
        { "x", -8.0f },
        { "y", -3.5f }
    }),
    matjson::makeObject({
        { "blend", true },
        { "fade", 0.105f },
        { "stroke", 28.6f },
        { "interval", 1.0f / 24.0f },
        { "x", -14.0f },
        { "y", -3.0f }
    }),
    matjson::makeObject({
        { "blend", true },
        { "fade", 0.09f },
        { "stroke", 18.7f },
        { "interval", 1.0f / 20.0f },
        { "x", -14.0f },
        { "y", -3.0f }
    }),
    matjson::makeObject({
        { "blend", true },
        { "fade", 0.096f },
        { "stroke", 27.0f },
        { "interval", 1.0f / 24.0f },
        { "x", -14.0f },
        { "y", -2.5f }
    })
};

matjson::Value defaultShipFire = matjson::makeObject({
    { "blend", true },
    { "fade", 0.1f },
    { "stroke", 20.0f },
    { "interval", 0.05f },
    { "x", -8.0f },
    { "y", -3.0f }
});

const matjson::Value& Defaults::getShipFireInfo(int id) {
    auto index = id - 2;
    return index >= 0 && index < shipFires.size() ? shipFires[index] : defaultShipFire;
}

int Defaults::getShipFireCount(int id) {
    switch (id) {
        case 2: return 9;
        case 3: return 10;
        case 4: return 6;
        case 5: return 16;
        case 6: return 5;
        default: return 0;
    }
}
