name: Deploy Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Documentation
    runs-on: windows-latest

    steps:
      - name: Checkout More Icons
        uses: actions/checkout@v4
        with:
          path: ./MoreIcons

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Download Flash
        uses: robinraju/release-downloader@v1.11
        with:
          repository: geode-sdk/flash
          latest: true
          fileName: flash.exe

      - name: Setup Geode CLI
        uses: geode-sdk/cli/.github/actions/setup@main

      - name: Get Geode Version
        id: geode
        shell: bash
        run: |
          cd MoreIcons
          GEODE_VERSION=$(jq -r '.geode' mod.json)
          GEODE_VERSION=v${GEODE_VERSION#v}
          echo "Geode Version: $GEODE_VERSION"
          # set GITHUB_OUTPUT
          echo "version=$GEODE_VERSION" >> $GITHUB_OUTPUT

      - name: Generate Documentation
        run: |
          geode sdk install "${{ github.workspace }}/geode"
          export GEODE_SDK="${{ github.workspace }}/geode"
          echo "GEODE_SDK=$GEODE_SDK" >> $GITHUB_ENV
          geode sdk update ${{ steps.geode.outputs.version }} && geode sdk install-binaries
          mkdir dist
          mv ./MoreIcons/fix-docs.js ./dist/fix-docs.js
          cd dist
          ../flash.exe -i ../MoreIcons -o . --overwrite && node ./fix-docs.js

      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
        
      - name: Deploy Pages
        uses: actions/deploy-pages@v4
